### ISSUE TITLE
Ability to handle large volume of edges and nodes

### ISSUE THREAD

**Issue by karrtikiyer** [thomasp85/ggraph#234]
Hi Thomas,
I had.a question, I have a graph with 4830 nodes and 172094 edges. And I am trying to plot this graph using ggraph and RStudio takes infinite time and potentially hangs.
If I filter the graph to have only to have 200 nodes it works. 
The layout that I am using is auto. And I have create a graph using tidygraph
`tbl_graph(nodes = nodes, edges = edges, directed = TRUE)`
`library(ggraph)
ggraph(my_graph, layout = "auto") +
    geom_edge_link() +
    geom_node_label(aes(label = str_sub(label,1, 1), colour = type))`
Also I am trying the above code in a RNotebook.
Is there any limitation which you are aware of?

**Comment by schochastics** [comment]
This is not (necessarily) a limitation of ggraph but a limitation of layout algorithms. Checkout the [graphlayouts](http://graphlayouts.schochastics.net/) package for algorithms that work with larger graphs. Also, use `geom_edge_link0` instead of `geom_edge_link()`. geom_edge_link creates 100 points per edge while drawing, geom_edge_link0 only 2. This speeds up the drawing process by quite a lot

So try:
```r
ggraph(my_graph, layout = "pmds") +
 geom_edge_link0() + 
 geom_node_label(aes(label = str_sub(label,1, 1), colour = type))
```
or

```r
ggraph(my_graph, layout = "sparse_stress") +
 geom_edge_link0() + 
 geom_node_label(aes(label = str_sub(label,1, 1), colour = type))
```
after installing `graphlayouts`
