### ISSUE TITLE
Feature request: facet_components

### ISSUE THREAD

**Issue by wdkrnls** [thomasp85/ggraph#239]
The current faceting tools force keeping all nodes presented (if invisibly) on all facets. I'm looking for the functionality to analyze my graph by breaking it up into subgraphs. My strategy so far has been to try and isolate these subgraphs by cutting edges to produce completely disconnected components. I have managed a hack using `facet_nodes` which only shows the nodes and edges of each component, but each facet has massive whitespace gaps where the other components would be. Reading through issue #136 it seems that my request is slightly different, because I not only want to change what nodes (and edges) appear across facets, but also seek to reposition the location of nodes shown across each facet to focus on each component in isolation. Does that make sense? I suspect you might want a new facetting function `facet_components` to do this. I would also prefer to have some way to show groups of similar components shown together in a `facet_grid` style arrangement as well.

**Comment by mkoohafkan** [comment]
I think this will be related to [`igraph::component_wise`](https://igraph.org/r/doc/component_wise.html). Or perhaps it involves adding an offset to the coordinates generated by `create_layout()`, so that the result is achievable via `facet_wrap(scales = "free")`.

Technically, this is possible using just `facet_wrap(), you just need to assign the component ID to both the nodes and the edges have the same attribute:

```
g1 = create_ring(10) %>%
  mutate(label = "A") %E>%
  mutate(label = "A")
g2 = create_ring(5) %>%
  mutate(label = "B") %E>%
  mutate(label = "B")

g = bind_graphs(g1, g2)
ggraph(g) +
  geom_edge_link() +
  geom_node_point() +
  facet_wrap(~label, scales = "free")
```
![image](https://user-images.githubusercontent.com/4790348/97384005-0bf49b00-188c-11eb-937a-9aff54bf62b7.png)

**Comment by thomasp85** [comment]
You can do this directly with `facet_nodes()` using tidygraph algorithms

``` r
g <- bind_graphs(create_ring(10), create_ring(5))
ggraph(g) +
  geom_edge_link() +
  geom_node_point() +
  facet_nodes(~tidygraph::group_components(), scales = "free")
#> Using "stress" as default layout
```

![](https://i.imgur.com/TbVdDn4.png)
